name = "CHEASE"
uuid = "40781a8e-f1bb-11ec-24ef-0f6bc40c1567"
authors = ["Tim Slendebroek <tim@slendebroek.com>"]
version = "1.1.1"

[deps]
EFIT = "cda752c5-6b03-55a3-9e33-132a441b0c17"
MXHEquilibrium = "8efa4e5a-7b9a-4eec-876e-01d13d5b5d75"

[compat]
EFIT = "1"
MXHEquilibrium = "1"
