name: Make Docs
on:
  pull_request:
    branches: ["master"]
  push:
    branches:
      - master
      - docs
    paths:
      - '.github/workflows/make_docs.yml'
      - 'src/'
      - 'docs/**'
    tags: '*'
  workflow_dispatch:
    
jobs:
  make_docs:
    permissions:
      contents: write
      statuses: write
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
      - uses: julia-actions/cache@v1
      - name: Install dependencies
        run: |
          julia -e '
            using Pkg
            Pkg.activate(".")
            
            dependencies = PackageSpec[]
            for package in ("CoordinateConventions", "EFIT", "Fortran90Namelists", "MXHEquilibrium", "MeshTools", "MillerExtendedHarmonic")
              push!(dependencies, PackageSpec(url="https://project-torrey-pines:${{secrets.PTP_READ_TOKEN}}@github.com/ProjectTorreyPines/$package.jl.git"))
            end
            Pkg.add(dependencies)

            Pkg.instantiate()
            '
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=docs/ docs/make.jl